from pathlib import Path


def replace_once(text: str, old: str, new: str, label: str) -> str:
    count = text.count(old)
    if count != 1:
        raise RuntimeError(f'{label}: expected one match, found {count}')
    return text.replace(old, new, 1)

product_path = Path('src/components/features/Product/ProductDetailDrawer.tsx')
product = product_path.read_text()
product = replace_once(product, 'import { findSimilarProducts } from "@/services/mathUtils";', 'import { findSimilarProducts, parseFiniteNumericValue } from "@/services/mathUtils";', 'mathUtils import')
product = replace_once(product, '''    return findSimilarProducts(displayProduct, allProducts, (p, key) => {\n      const raw = p.properties[key]?.value;\n      const num = typeof raw === "number" ? raw : parseFloat(String(raw));\n      return isNaN(num) ? null : num;\n    }).slice(0, 3);''', '''    return findSimilarProducts(\n      displayProduct,\n      allProducts,\n      (candidate, key) => parseFiniteNumericValue(candidate.properties[key]?.value),\n    ).slice(0, 3);''', 'strict similarity extractor')
product = replace_once(product, '''                           <SimilarProductsRadar \n                              targetProduct={displayProduct} \n                              similarProducts={similarProducts} \n                           />''', '''                           <SimilarProductsRadar\n                              targetProduct={displayProduct}\n                              similarProducts={similarProducts}\n                              allProducts={allProducts}\n                           />''', 'radar props')
product = replace_once(product, '''                              {similarProducts.map(\n                                ({ product: p, score: similarity }) => (\n                                  <motion.button''', '''                              {similarProducts.map(\n                                ({\n                                  product: p,\n                                  score: similarity,\n                                  sharedFeatureCount,\n                                  targetFeatureCount,\n                                }) => (\n                                  <motion.button''', 'overview destructuring')
product = replace_once(product, '''                                    <div className="text-[9px] font-mono font-bold text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-900/30 px-2 py-0.5 rounded-md border border-indigo-200 dark:border-indigo-800/50 uppercase tracking-widest shadow-sm">\n                                      {similarity}% Match\n                                    </div>''', '''                                    <div className="text-right shrink-0">\n                                      <div className="text-[9px] font-mono font-bold text-indigo-700 dark:text-indigo-300 bg-indigo-50 dark:bg-indigo-900/30 px-2 py-0.5 rounded-md border border-indigo-200 dark:border-indigo-800/50 uppercase tracking-widest shadow-sm">\n                                        {similarity}% Match\n                                      </div>\n                                      <div className="mt-1 text-[8px] font-mono text-slate-400">\n                                        {sharedFeatureCount}/{targetFeatureCount} shared features\n                                      </div>\n                                    </div>''', 'overview evidence')
product = replace_once(product, '''                          {similarProducts.map(({ product: p, score: similarity }) => (\n                            <motion.button''', '''                          {similarProducts.map(({\n                            product: p,\n                            score: similarity,\n                            sharedFeatureCount,\n                            targetFeatureCount,\n                          }) => (\n                            <motion.button''', 'similar-tab destructuring')
product = replace_once(product, '''                                <span className="text-[9px] font-mono font-bold text-emerald-600 dark:text-emerald-400 bg-white dark:bg-slate-950 border border-emerald-200 dark:border-emerald-800/50 px-1.5 py-0.5 rounded-md shadow-sm uppercase tracking-widest shrink-0">\n                                  {similarity}%\n                                </span>''', '''                                <div className="text-right shrink-0">\n                                  <span className="text-[9px] font-mono font-bold text-emerald-600 dark:text-emerald-400 bg-white dark:bg-slate-950 border border-emerald-200 dark:border-emerald-800/50 px-1.5 py-0.5 rounded-md shadow-sm uppercase tracking-widest">\n                                    {similarity}%\n                                  </span>\n                                  <p className="mt-1 text-[8px] font-mono text-slate-400">\n                                    {sharedFeatureCount}/{targetFeatureCount} dimensions\n                                  </p>\n                                </div>''', 'similar-tab evidence')
product_path.write_text('\n'.join(line.rstrip() for line in product.splitlines()) + '\n')

readme_path = Path('README.md')
readme = readme_path.read_text()
kmeans = '''### 5.17 K-Means\n\n$$\n\\min_{\\{c_i\\},\\{\\boldsymbol{\\mu}_k\\}}\n\\sum_{i=1}^{n}\n\\|\\boldsymbol{x}_i-\\boldsymbol{\\mu}_{c_i}\\|_2^2\n$$\n\n平台会记录 TypeScript/WASM 后端选择、设备校准、数值等价和实际运行证据。\n'''
readme = replace_once(readme, kmeans, kmeans + '''\n### 5.18 覆盖率约束的直接牌号推荐\n\n对目标牌号与候选牌号的共同有效属性执行全库 min-max 归一化，并计算 RMS 距离：\n\n$$\nd_{ab}=\\sqrt{\\frac{1}{|F_a\\cap F_b|}\n\\sum_{j\\in F_a\\cap F_b}\n(\\tilde{x}_{aj}-\\tilde{x}_{bj})^2}\n$$\n\n最终分数同时惩罚属性覆盖不足：\n\n$$\nS_{ab}=100\\times\\max(0,1-d_{ab})\\times\n\\frac{|F_a\\cap F_b|}{|F_a|}\n$$\n\n详情页会同时显示分数和共享维度数量；雷达图使用全局 0–100 归一化轴，不再把不同物理单位的原始数值混在同一半径尺度上。\n''', 'README formula')
readme = replace_once(readme, '| Similarity | 观测值样本方差、缺失掩码、重叠度惩罚与延迟边对象分配 | Z-score 余弦相似度 × 共享有效特征覆盖率 |', '| Similarity network | 观测值样本方差、缺失掩码、重叠度惩罚与延迟边对象分配 | Z-score 余弦相似度 × 共享有效特征覆盖率 |\n| Direct grade recommender | 稀疏单遍 min/max、目标特征缓存、覆盖率惩罚、稳定排序 | Min-max RMS 距离 × 目标属性覆盖率 |', 'README performance row')
readme = replace_once(readme, '- 直接 KDE `200,000 × 101` 夹具：约 `253.8 ms → 204.7 ms`，差异处于浮点重排量级。', '- 直接 KDE `200,000 × 101` 夹具：约 `253.8 ms → 204.7 ms`，差异处于浮点重排量级；\n- 直接牌号推荐稀疏 `10,000 × 120` 联合属性夹具：约 `397.94 ms → 11.46 ms`；稠密 `5,000 × 24` 夹具：约 `16.48 ms → 11.90 ms`。', 'README benchmark')
readme = replace_once(readme, '- 相似度采用共享有效特征覆盖率惩罚，仍不等于化学等价；', '- 相似度网络和直接牌号推荐均采用共享有效特征覆盖率惩罚，仍不等于化学等价或可互换性；\n- 详情页雷达图是全局 min-max 归一化轮廓，0–100 不代表绝对性能百分比；', 'README boundary')
readme_path.write_text(readme)
