import type { EChartsOption } from '@/lib/echarts';
import { materialEngine } from '@/lib/materialScience';
import { SCIENTIFIC_PALETTE,escapeScientificHtml,formatScientificNumber,scientificMutedColor } from './scientificFigurePolicy';
type AshbySeries={name:string;data:[number,number,string][]}; type AshbyInput={series?:AshbySeries[];xAxis?:string;yAxis?:string;xBounds?:{min:number;max:number};yBounds?:{min:number;max:number}};
export const getAshbyChartOption=(data:AshbyInput|unknown[],theme:'light'|'dark',language:'zh'|'en'='zh'):EChartsOption=>{
 const source=Array.isArray(data)?{}:data; const seriesData=(Array.isArray(data)?data:source.series??[]) as AshbySeries[]; const xAxisName=source.xAxis??(language==='en'?'Property X':'性能 X'); const yAxisName=source.yAxis??(language==='en'?'Property Y':'性能 Y');
 const allPoints=seriesData.flatMap(s=>s.data).map(p=>[Number(p[0]),Number(p[1])] as [number,number]).filter(([x,y])=>Number.isFinite(x)&&Number.isFinite(y)&&x>0&&y>0); const correlation=allPoints.length>5?materialEngine.analyzeCorrelationLog(allPoints):null;
 let min=Infinity,max=-Infinity; for(const [x] of allPoints){min=Math.min(min,x);max=Math.max(max,x);} const minX=source.xBounds?.min??(Number.isFinite(min)?min:.1); const maxX=source.xBounds?.max??(Number.isFinite(max)?max:100); const fitData:[number,number][]=[];
 if(correlation&&minX>0&&maxX>minX){const a=Math.log10(minX),b=Math.log10(maxX);for(let i=0;i<48;i++){const x=10**(a+i/47*(b-a)),y=correlation.regressionFn(x);if(Number.isFinite(y)&&y>0)fitData.push([x,y]);}}
 const candidates=seriesData.flatMap(s=>s.data).map(p=>({x:Number(p[0]),y:Number(p[1]),name:String(p[2])})).filter(p=>p.x>0&&p.y>0); const pareto=new Set(materialEngine.getParetoPoints(candidates)); const count=seriesData.reduce((n,s)=>n+s.data.length,0);
 return {title:{text:language==='en'?'Ashby property map':'Ashby 性能映射',subtext:correlation?(language==='en'?`Log–log power-law fit shown as a model: R²=${correlation.r2.toFixed(3)}`:`虚线为对数域幂律拟合模型：R²=${correlation.r2.toFixed(3)}`):(language==='en'?'Observed positive values only; no fit is shown.':'仅绘制正值观测点；样本不足时不显示拟合。'),left:'center',top:6,textStyle:{fontSize:14,fontWeight:650},subtextStyle:{color:scientificMutedColor(theme),fontSize:10}},grid:{left:70,right:36,bottom:70,top:72,containLabel:true},legend:{bottom:4},dataZoom:[{type:'inside',xAxisIndex:0,filterMode:'filter'},{type:'inside',yAxisIndex:0,filterMode:'filter'}],tooltip:{trigger:'item',formatter:(params:{seriesType?:string;value?:unknown})=>{if(params.seriesType==='line')return language==='en'?'Log–log power-law fit (model)':'对数域幂律拟合（模型）';const v=params.value as [number,number,string]|undefined;if(!v)return '';return `<strong>${escapeScientificHtml(v[2])}</strong><br/>${escapeScientificHtml(xAxisName)}: ${formatScientificNumber(Number(v[0]))}<br/>${escapeScientificHtml(yAxisName)}: ${formatScientificNumber(Number(v[1]))}${pareto.has(String(v[2]))?'<br/><b>Non-dominated observation</b>':''}`;}},xAxis:{type:'log',name:xAxisName,nameLocation:'middle',nameGap:34,min:source.xBounds?.min,max:source.xBounds?.max},yAxis:{type:'log',name:yAxisName,nameLocation:'middle',nameGap:48,min:source.yBounds?.min,max:source.yBounds?.max},series:[...seriesData.map((s,i)=>({name:s.name,type:'scatter' as const,symbolSize:count>3000?4:7,progressive:2000,large:count>8000,itemStyle:{opacity:.72,color:SCIENTIFIC_PALETTE[i%SCIENTIFIC_PALETTE.length]},data:s.data.filter(p=>Number(p[0])>0&&Number(p[1])>0)})),...(fitData.length?[{name:'Power-law fit (model)',type:'line' as const,data:fitData,lineStyle:{type:'dashed' as const,color:scientificMutedColor(theme),width:1.5},symbol:'none',silent:true}]:[])]};
};
