import type { Language } from '@/types/index';

export const scientificUiOverrides: Record<Language, Record<string, string>> = {
  zh: {
    localWorkspace: '本地工作区',
    browserMaterialsWorkspace: '浏览器材料数据工作区',
    workspaceDataNotice: 'ResinDB 正在当前浏览器中运行。请先核对实时记录数量、数据来源、单位与测试条件，再根据工作区数据作出判断。',
    initiateSession: '进入工作区',
    demoWorkspaceNotice: '演示工作区 · 请核验源数据',
    dismissWelcome: '关闭欢迎提示',
    workspaceRoot: '主页 / RESIN.DB',
    workspaceWarehouse: '数据中心',
    workspaceAnalysis: '科研分析',
    qualityFilterLabel: '数据质量',
    qualityFilterAll: '全部',
    qualityFilterAny: '不限',
    chart_feature_importance: '岭回归敏感度归因',
    desc_feature_importance: '标准化岭回归系数的条件关联归因；不表示因果关系，也不是 SHAP。',
    materialDurabilityForecast: '材料耐久情景投影',
    predictiveTrends: '合成趋势情景',
    resinCapacityForecast: '产能情景分析',
    sysHealthSubtitle: '系统健康与版本',
    sysHealthNoEvents: '暂无同步日志',
  },
  en: {
    localWorkspace: 'Local workspace',
    browserMaterialsWorkspace: 'Browser-based materials data workspace',
    workspaceDataNotice: 'ResinDB is running in the current browser. Review live record counts, data provenance, units, and test conditions before drawing conclusions from the workspace.',
    initiateSession: 'Initiate session',
    demoWorkspaceNotice: 'Demo workspace · verify source data',
    dismissWelcome: 'Dismiss welcome message',
    workspaceRoot: 'Home / RESIN.DB',
    workspaceWarehouse: 'Data warehouse',
    workspaceAnalysis: 'Research analysis',
    qualityFilterLabel: 'Data quality',
    qualityFilterAll: 'All',
    qualityFilterAny: 'Any',
    chart_feature_importance: 'Ridge sensitivity attribution',
    desc_feature_importance: 'Conditional association from standardized ridge coefficients; not causality or SHAP.',
    materialDurabilityForecast: 'Material durability scenarios',
    predictiveTrends: 'Synthetic trend scenarios',
    resinCapacityForecast: 'Capacity scenario analysis',
    sysHealthSubtitle: 'System health and versioning',
    sysHealthNoEvents: 'No recent synchronization events',
  },
};
