name: Remove temporary audit branch

on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  contents: write

jobs:
  remove-branch:
    if: github.event.pull_request.head.ref == 'audit-trigger'
    runs-on: ubuntu-latest
    steps:
      - name: Delete temporary branch
        shell: bash
        run: git push https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git --delete audit-trigger || true
